export const productImages = [
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
];

export const swiperImages = [
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/parallax5.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/ring.png',
    '/images/meteora.png',
    '/images/meteora.png',
    '/images/meteora.png',
    '/images/meteora.png',
    '/images/meteora.png',
];