# Имя вашего workflow
name: Deploy Frontend to VDS

# Триггер для запуска
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
      - name: Build project
        # Добавляем этот блок 'env', чтобы сделать секрет доступным
        # как переменную окружения во время выполнения команды 'run'
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: npm run build

      # --- КОНЕЦ ИЗМЕНЕНИЙ ---

      - name: Deploy to VDS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          # Ваша команда `next build && next export` создает папку 'out'.
          # Поэтому этот путь указан правильно.
          source: "./out/*"
          target: "/root/my_project/frontend_build"
          strip_components: 1